name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: lamer1
        password: {{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and push
      run: docker push kaspa-rest-wallet:$(date +%s)
