name: Docker Image CI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Name of build
        default: test
        required: false

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: lamer1
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: supertypo/kaspa-rest-server:${{github.ref_name}}, supertypo/kaspa-rest-server:latest
          file: ./docker/Dockerfile
          build-args: |
            version=${{github.ref_name}}
